config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: 'cambios#new'

  resources :cambios do
  	member do
  		get 'cancelar'
  		get 'procesada'
  	end
  end
  resources :users, only: [:show] do
    resources :accounts
  end
end

app/models/account.rb
class Account < ApplicationRecord
    belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cambio.rb
class Cambio < ApplicationRecord
	enum status: [ :pendiente, :aceptada, :ejecutada ]
	belongs_to :user, optional: true
	has_many :comentarios

	def self.per_page
		10
	end
end

app/models/comentario.rb
class Comentario < ApplicationRecord
	belongs_to :cambio
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
  has_many :cambios
  has_many :accounts
  has_many :comentarios

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :find_user, only: [:index, :new, :create]
  #skip_before_action :authenticate_user!
  
  def index
    @accounts = Account.where(user_id: params[:user_id])
    respond_to do |format|
      format.html
      format.json { render :json => @accounts }
    end

  end
  
  def new
    @account = @user.accounts.new
  end

  def create
    @account = @user.accounts.build(accounts_params)
    if @account.save
      flash[:notice] = "Cuenta de beneficiario guardada"
      redirect_to root_path 
    end
  end

  def show
    @account = Account.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @account }
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def find_user
    @user ||= current_user
    if @user == nil
      redirect_to new_user_session_path
    end
  end

  def accounts_params
    params.require(:account).permit!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cambios_controller.rb
class CambiosController < ApplicationController
	skip_before_action :verify_authenticity_token
	
	require 'khipu-api-client'
    before_action :find_user, only: [:index, :new, :create, :edit]
    before_action :find_cambio, only: [:cancelar, :procesada, :edit, :update]
    before_action :set_locale
    before_action :correct_user, only: [:edit]
	def index
		if find_user
			@cambios = find_user.admin ? Cambio.where(status: "pendiente").paginate(:page => params[:page]).order("id DESC") : Cambio.where(user_id: find_user.id).paginate(:page => params[:page]).order("id DESC")
		else
			flash[:alert] = I18n.t :need_login
			redirect_to new_user_session_path
		end
	end

	def new
		@rate = get_rate
		if find_user == nil
			@cambio = Cambio.new
		else
			@cambio = @user.cambios.new
		end
	end

	def create
		if  params["account"].first.empty? != true
			@account_id = params["account"].first
			@account = Account.find(@account_id)
			@cambio = @user.cambios.build(nombre: @account.nombre, banco: @account.banco, cuenta: @account.cuenta, cedula: @account.cedula, email: @account.email, tipo_de_cuenta: @account.tipo_de_cuenta, bolivares: params[:cambio][:bolivares], pesos: params[:cambio][:pesos], taza: params[:cambio][:taza])
		else
		    @cambio = @user.cambios.build(cambio_params)
		end
		if @cambio.save
			CambioMailer.cambio_mailer(@cambio).deliver_now
			khipu_config
			khipu_payment(@cambio,@user)
			#CambioMailer.cambio_mailer(@cambio).deliver_now
		else
			render "new"
		end
	end

	def edit
	end

	def update
		@cambio.update(cambio_params)
		redirect_to cambios_path
	end

	def show
		@cambio = Cambio.find(params[:id])
	end

	def cancelar
		@cambio.destroy
		flash[:notice] = "Su cambio no pudo ser procesado"
		redirect_to new_cambio_path
	end

	def procesada
		flash[:notice] = "Solicitud Creada"
		redirect_to new_cambio_path
	end

	private

	def get_rate
		GetRateService.new.rate_calculation
	end

	def cambio_params
		params.require(:cambio).permit!
	end

	def find_user
		@user ||= current_user
	end

	def set_locale
		I18n.locale = params[:locale] || I18n.default_locale
	end

	def khipu_config
		receiver_id = 154596
		secret_key = '619e46972f700e28aee2c0c73bed6576750ba56a'
		Khipu.configure do |c|
		  c.secret = secret_key
		  c.receiver_id = receiver_id
		  c.platform = 'mi casa de acmbio'
		  c.platform_version = '2.0'
		  # c.debugging = true
		end
	end

	def find_cambio
		@cambio = Cambio.find(params[:id])
	end

	def khipu_payment(cambio, usuario)
		@motivo = "Envio de Bsf #{cambio.bolivares.floor}"
		@transaction_id = "#{cambio.id}"
		@valor = cambio.pesos
		@usuario = usuario.email
		client = Khipu::PaymentsApi.new
		response = client.payments_post(@motivo, 'CLP', @valor, {
			transaction_id: "#{@transaction_id}",
			picture_url: "http://fotos.e-consulta.com/remesas_3_0_0_0.jpg",
			expires_date: DateTime.now + 0.0104,
		    payer_email: "#{@usuario}",
		    send_email: false,
		    send_reminders: false,
		    return_url: root_url+"/cambios/#{@transaction_id}/procesada",
		    cancel_url: root_url+"/cambios/#{@transaction_id}/cancelar"
		})
		redirect_to response.transfer_url
	end

	def correct_user
      unless @user.admin
      	flash[:notice] = "Usuario debe ser administrador"
      	redirect_to cambios_path
      end
	end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cambios_helper.rb
module CambiosHelper
end

app/views/accounts/new.html.haml
%h2 Agregar nueva cuenta de beneficiario

= form_for [@user, @account] do |f|
  = f.text_field :nombre, placeholder: "Nombre del beneficiario"
  - bancos = [["Banesco", "Banesco"], ["Venezuela", "Venezuela"]]
  = f.select :banco, options_for_select(bancos)
  - tipo_de_cuenta = [["Ahorro", "Ahorro"], ["Corriente", "Corriente"]]
  = f.select :tipo_de_cuenta, options_for_select(tipo_de_cuenta)
  = f.text_field :cuenta, placeholder: "Numero de Cuenta"
  = f.text_field :cedula, placeholder: "Numero de Cedula"
  = f.text_field :email, placeholder: "Email"
  = f.submit "Guardar"

app/views/cambios/edit.html.haml
#historial
  %h2 Historial de cambios
  .jumbotron
    .row#envio
      .col-md-1
        %h5 ID
        = @cambio.id
      .col-md-2
        %h5 Fecha
        = @cambio.created_at.strftime("%b %d, %Y")
      .col-md-2
        %h5 Taza
        = "#{number_with_delimiter(@cambio.taza.to_i, :delimiter => '.')} CLP/BsF"
      .col-md-2
        %h5 Bolivares
        = "BsF #{number_with_delimiter(@cambio.bolivares.to_i, :delimiter => '.')}"
        %br
        %small.text-success= "#{@cambio.banco}"
      .col-md-2
        %h5 Pesos
        = "$ #{number_with_delimiter(@cambio.pesos.to_i, :delimiter => '.')}"
      .col-md-2
        %h5 Estado
        .btn.btn-primary= @cambio.status
    .row#infoDeEnvio
      = form_for @cambio do |f|
        .bg-success#datosDeEnvio
          %h5= "Cuenta: #{@cambio.cuenta}"
          %h5= "Banco: #{@cambio.banco}"
          %h5= "Nombre: #{@cambio.nombre}"
          %h5= "Cedula: #{@cambio.cedula}"
          %h5= "Tipo de Cuenta: #{@cambio.tipo_de_cuenta}"
        %h5 Estado
        .row
          .col-md-4
            = f.radio_button :status, "pendiente"
            %br Pendiente
          .col-md-4
            = f.radio_button :status, "aceptada"
            %br Aceptada
          .col-md-4
            = f.radio_button :status, "ejecutada"
            %br Ejecutada
        = f.submit "Guardar", class: "btn btn-primary"

app/views/cambios/index.html.haml
#historial
  %h2 Historial de cambios
  .jumbotron
    = will_paginate @cambios, class: "flickr_pagination"
    - @cambios.each do |cambio|
      .row#envio
        .col-md-2
          %h5 Fecha
          = cambio.created_at.strftime("%b %d, %Y")
        .col-md-2
          %h5 Taza
          = "#{number_with_delimiter(cambio.taza.to_i, :delimiter => '.')} CLP/BsF"
        .col-md-2
          %h5 Bolivares
          = "BsF #{number_with_delimiter(cambio.bolivares.to_i, :delimiter => '.')}"
          %br
          %small.text-success= "#{cambio.banco}"
        .col-md-2
          %h5 Pesos
          = "$ #{number_with_delimiter(cambio.pesos.to_i, :delimiter => '.')}"
        .col-md-2
          %h5 Estado
          .btn.btn-primary= cambio.status
        .col-md-2
          - if current_user.admin
            %h5= link_to "Ver Mas", edit_cambio_path(cambio)
          - else
            %h5= link_to "Ver Mas", cambio_path(cambio)

app/views/cambios/new.html.haml
- if user_signed_in?
  #formularioDeCambio
    = form_for @cambio do |f|
      %h4= "Tasa #{@rate.floor}"
      = f.text_field :pesos, placeholder: "Pesos"
      = " = "
      = f.text_field :bolivares, placeholder: "Bolivares"
      #alerta
      = f.hidden_field :taza
      %br
      %h4 Datos para transferir
      = f.text_field :nombre, placeholder: "Nombre"
      %br
      = select(:account, nil, Account.where(user_id: @user).collect {|p| [ p.nombre+" "+p.banco, p.id ] }, {prompt: 'Seleccionar Beneficiario'})
      - bancos = [["Banesco", "Banesco"], ["Venezuela", "Venezuela"]]
      = f.select :banco, options_for_select(bancos)
      - tipo_de_cuenta = [["Ahorro", "Ahorro"], ["Corriente", "Corriente"]]
      = f.select :tipo_de_cuenta, options_for_select(tipo_de_cuenta)
      %br
      = f.text_field :cuenta, placeholder: "Numero de Cuenta"
      %br
      = f.text_field :cedula, placeholder: "Cedula"
      %br
      = f.text_field :email, placeholder: "Email"
      %br
      = f.submit "Cambiar", class:"btn btn-success"
    %input#hidden{ value:@user.id, type:"hidden"}

    / Button trigger modal
    %button.btn.btn-primary{"data-target" => "#exampleModal", "data-toggle" => "modal", :type => "button"}
      ¿Cómo funciona?
  / Modal
  #exampleModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
    .modal-dialog{:role => "document"}
      .modal-content
        .modal-header
          %h5#exampleModalLabel.modal-title ¿Cómo funciona?
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
        .modal-body
          \...
        .modal-footer
          %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Cerrar
- else
  .container#banner
    .jumbotron
      %h2 Enviar dinero a Venezuela facil y rapido
      %p.text-center= link_to "Iniciar Sesion", new_user_session_path, class:"btn btn-primary btn-lg"

app/views/cambios/show.html.haml
= @cambio.banco

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SafeMoney
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{ name: "viewport", content: "width=device-width, initial-scale: 1" }
  %body
    %nav.navbar.navbar-expand-lg.navbar-light.bg-light
      = link_to "SafeMoney", root_path, class:"navbar-brand col-md-2"
      %ul.navbar-nav.mr-auto
        Taza Actual: 1 CLP =
        %strong.text-success#rate
          - if @rate
            ="#{@rate.floor}"
      %ul.navbar-nav.ml-auto
        - if user_signed_in?
          %li
            %strong= "#{current_user.email}"
        - if !user_signed_in?
          %li= link_to "Iniciar Sesion", new_user_session_path, class:"btn btn-primary"
          %li= link_to "Unirse", new_user_registration_path, class:"btn btn-success"
        - if user_signed_in?
          %li= link_to "Historial", cambios_path, class:"btn btn-info"
          %li= link_to "Salir", destroy_user_session_path, class:"btn btn-warning", method: :delete
    .container-fluid
      .row
        .col-md-1#history
          -if user_signed_in?
            %i.fa.fa-history
            = link_to "Historial de envios", cambios_path
            %br
            %i.fa.fa-address-book-o
            = link_to "Cuentas guardadas", new_user_account_path(@user)
        .col-md-11#main-content
          - if flash[:notice]
            .alert.alert-success= notice
          - if flash[:alert]
            .alert.alert-success= alert
          = yield